feat(gch): write breaking changes to output file

diff --git a/gch b/gch
--- a/gch
+++ b/gch
@@ -109,10 +109,18 @@ for commit_type in "${commit_types[@]}"; do
       commit_message=$(echo "$commit_content" | cut -d ':' -f2- | sed 's/^ *//')
       commit_body=$(git log -n 1 --pretty=format:'%b' "$commit_hash")
       commit_refs=$(echo "$commit_body" | grep -o '#[0-9]\+' | tr '\n' ',' | sed 's/,$//')
-      commit_break=$(echo "$commit_content" | grep "^${commit_type}${commit_scope:+(.\+)}!:" || echo "$commit_body" | grep -i "breaking change")
-      [ -n "$commit_break" ] && major_update=true || [ "$commit_type" == "feat" ] && minor_update=true
+      commit_break=$(echo "$commit_content" | grep "^${commit_type}${commit_scope:+(.\+)}!:" || echo "$commit_body" | grep -i "breaking change:.\+")
       commit_entry="- ${commit_break:+[⚠] }${commit_scope:+**${commit_scope}:** }${commit_message} ${commit_refs:+(${commit_refs}) }([${commit_hash}](${repo_url}/commit/${commit_hash}))"
       echo "$commit_entry" >> "$output_file" || throw_error "failed to write to ${output_file} file"
+      if [ -n "$commit_break" ]; then
+        breaking_changes=$(echo "$commit_body" | grep -oi 'breaking change:.\+' | sed 's/^breaking change: */  - \*\*BREAKING CHANGE:\*\* /gi')
+        if [ -n "$breaking_changes" ]; then
+          echo "$breaking_changes" >> "$output_file" || throw_error "failed to write to ${output_file} file"
+        fi
+        major_update=true
+      elif [ "$commit_type" == "feat" ]; then
+        minor_update=true
+      fi
       ((total_commits_written_count++))
       ((section_commits_written_count++))
       printf "\r%-25s${BLUE}--> ${section_commits_written_count} commit(s) written${RESET}" "$section"
