refactor: clean code

diff --git a/gch b/gch
--- a/gch
+++ b/gch
@@ -5,13 +5,13 @@ set -o pipefail
 
 # Configure colors
 RESET="\033[0m" # Reset color
-GRAY="\033[0;30m" # Gray
-RED="\033[0;31m" # Red
-GREEN="\033[0;32m" # Green
-YELLOW="\033[0;33m" # Yellow
+GRAY="\033[30m" # Gray
+RED="\033[31m" # Red
+GREEN="\033[32m" # Green
+YELLOW="\033[33m" # Yellow
+BLUE="\033[34m" # Blue
+CYAN="\033[36m" # Cyan
 ORANGE="\033[38;5;208m" # Orange
-BLUE="\033[0;34m" # Blue
-CYAN="\033[0;36m" # Cyan
 
 # Print sucess message
 print_success() {
@@ -58,9 +58,9 @@ total_commits_count=$(git rev-list ${last_version:+${last_version}...}HEAD --no-
 # Get output file
 output_file=$(jq -r ".output_file" "$config_file")
 [[ -z "$output_file" || "$output_file" == "null" ]] && print_warn "output file not found in config file" && output_file="CHANGELOG.md"
+echo -e "${YELLOW}Output file:${RESET} ${output_file}"
 
 # Ask user for choose another output file
-echo -e "${YELLOW}Output file:${RESET} ${output_file}"
 ask_user "Choose another file ?" "press [Enter] to skip"
 read -r another_output_file
 [ -n "$another_output_file" ] && output_file="$another_output_file"
@@ -112,7 +112,7 @@ for commit_type in "${commit_types[@]}"; do
       breaking_change=$(echo "$commit_content" | grep "^${commit_type}${commit_scope:+(.\+)}!:" || echo "$commit_body_footer" | grep -i "breaking change")
       [ -n "$breaking_change" ] && major_update=true || [ "$commit_type" == "feat" ] && minor_update=true
       commit_entry="- ${breaking_change:+[⚠️ BREAKING CHANGE] }${commit_scope:+**${commit_scope}:** }${commit_message} ${commit_refs:+(${commit_refs}) }([${commit_hash}](${repo_url}/commit/${commit_hash}))"
-      echo "${commit_entry}" >> "$output_file" || throw_error "failed to write to ${output_file} file"
+      echo "$commit_entry" >> "$output_file" || throw_error "failed to write to ${output_file} file"
       ((total_commits_written_count++))
       ((section_commits_written_count++))
       printf "\r%-25s${BLUE}--> ${section_commits_written_count} commit(s) written${RESET}" "$section"
@@ -134,7 +134,7 @@ if [ -n "$nc_commits" ]; then
     commit_hash=$(echo "$commit" | cut -d ' ' -f1)
     commit_content=$(echo "$commit" | cut -d ' ' -f2-)
     commit_entry="- ${commit_content} ([${commit_hash}](${repo_url}/commit/${commit_hash}))"
-    echo -e "${commit_entry}" >> "$output_file" || throw_error "failed to write to ${output_file} file"
+    echo "$commit_entry" >> "$output_file" || throw_error "failed to write to ${output_file} file"
     ((total_commits_written_count++))
     ((nc_commits_written_count++))
     printf "\r${RED}%-25s--> ${nc_commits_written_count} commit(s) written${RESET}" "$nc_section"
@@ -169,14 +169,10 @@ ask_user "Choose another version?" "press [Enter] to skip"
 read -r another_version
 [ -n "$another_version" ] && new_version="$another_version"
 
-# Get comparison URL if last version exists and write changelog title at the beginning of output file
-if [ -n "$last_version" ]; then
-  comparison_url="${repo_url}/compare/${last_version}...${new_version}"
-  echo "# Release [${new_version}](${comparison_url}) ($(date +'%Y-%m-%d'))" | cat - "$output_file" > temp && mv temp "$output_file"
-else
-  echo "# Release ${new_version} ($(date +'%Y-%m-%d'))" | cat - "$output_file" > temp && mv temp "$output_file"
-fi
-print_success "changelog ${new_version} generated!"
+# Write changelog title at beginning of output file
+title_entry="# Release $([ -n "$last_version" ] && echo "[${new_version}](${repo_url}/compare/${last_version}...${new_version})" || echo "${new_version}") ($(date +'%Y-%m-%d'))"
+echo "$title_entry" | cat - "$output_file" > temp && mv temp "$output_file" || throw_error "failed to write to ${output_file} file"
+print_success "new changelog ${new_version} generated"
 
 # Ask user for bump version
 ask_user "Bump version?" "[Y/n]"
